### PR TITLE
Add all pull requests to one request

### PR DESCRIPTION
**Pull request by b4ldr**
Hi this pull request merges a few different pulls into one, not merged exactly but gets the general functionality
    \* https://github.com/rodjek/puppet-logrotate/pull/43
    \* https://github.com/rodjek/puppet-logrotate/pull/41
    \* https://github.com/rodjek/puppet-logrotate/pull/38
    \* https://github.com/rodjek/puppet-logrotate/pull/32
    \* https://github.com/rodjek/puppet-logrotate/pull/15
As far as i can tell it also fixes 
    \* https://github.com/rodjek/puppet-logrotate/issues/50

### CODE REVIEW

**Comment by lavoiesl** [comment]
@rodjek  Can we get some exposure on this? I need it for Ubuntu Trusty. Thanks.

**Comment by b4ldr** [comment]
@lavoiesl FYI i did a release on forge untill these things get merged

https://forge.puppetlabs.com/b4ldr/logrotate

**Comment by j1n6** [comment]
great!

**Comment by b4ldr** [comment]
i just noticed this old pull.  for the record im now using https://github.com/voxpupuli/puppet-logrotate

**Pull request closed without merging**
