### PR TITLE
Feature added: rotate_every => 'hour'

### PR DESCRIPTION
**Pull request by egeland**
We needed to be able to rotate some log files hourly,
based on their size.
Added this functionality, which also creates a cronjob and a dir
in which to keep the logrotate jobs.

Other changes:
Removed the vendor/cache/*.gem files and added them to .gitignore
Edited the defaults, added redhat defaults file.

### CODE REVIEW

**Comment by rodjek** [comment]
I like it, except for a few of things:
- I commit the files in vendor/cache specifically, please don't remove them.
- Tests, you've broken some and add some for your new functionality.
- Why did you change the defaults for debian from 1 copy to 3?  That is not what debian ships by default.

**Comment by egeland** [comment]
Hi @rodjek,
- I'll look at tests - I didn't really do anything with them, mainly because I have never looked at the tests before, so this is a good opportunity for me to learn about them.
- The gems, I can certainly put them back - just wondering what the reason for committing binaries is? It's a little unusual, in my experience, so I'd like to know what they are needed for?
- The 1 copy -> 3 change was to match our internal defaults - sorry it slipped in to this change.

I'll edit my commit and let you know when it's ready for review again.

**Comment by rodjek** [comment]
I vendor the gems into all my projects because I work offline a lot and even when I'm online, I don't trust the availability of rubygems.org.

**Comment by blkperl** [comment]
@rodjek I was wondering about that too, can you still vendor the gems and add them to the .gitignore?

**Comment by rodjek** [comment]
Sure, but I want them in the repo for portability.  I'm not sure why this is an issue for people, it's not like I include them in the packaged module on the forge.

**Comment by rodjek** [comment]
@egeland I've implemented hourly logrotate support in #11 in a similar style to what you have here.  I'm sorry but I can't merge your PR because there's just too many unrelated changes included and there's been no action on this PR for 3 months.

**Comment by egeland** [comment]
No worries - I hadn't found the time to do it properly, so I'm glad you took the idea and incorporated it with the module! :-)

**Pull request closed without merging**
